In [1]:
import json

data = '{"name": "홍길동", "age": 30, "isStudent": false}'
python_obj = json.loads(data)

print(python_obj)
print(python_obj["name"])

{'name': '홍길동', 'age': 30, 'isStudent': False}
홍길동

In [2]:
type(python_obj)

dict

In [3]:
import json

person = {
    "name": "이몽룡",
    "age": 25,
    "skills": ["Python", "React"]
}

json_str = json.dumps(person, ensure_ascii=False, indent=2)
print(json_str)

{
  "name": "이몽룡",
  "age": 25,
  "skills": [
    "Python",
    "React"
  ]
}

In [26]:
import requests

client_id = "발급받은_ID"
client_secret = "발급받은_SECRET"

url = "https://openapi.naver.com/v1/search/blog.json"

headers = {
    "X-Naver-Client-Id": "2DxEkSbobL_VQXzpcazR",
    "X-Naver-Client-Secret": "8Z7NlMumQj"
}

params = {
    "query": "파이썬",
    "display": 5
}

res = requests.get(url, headers=headers, params=params)
print(res.status_code)   # 200이면 성공

print(res.text)

result = res.json()
data = res.json()

200
{
	"lastBuildDate":"Fri, 28 Aug 2026 12:21:29 +0900",
	"total":788852,
	"start":1,
	"display":5,
	"items":[
		{
			"title":"[Python] <b>파이썬<\/b> 문법 (자료형)",
			"link":"https:\/\/angelplayer.tistory.com\/200",
			"description":"없음 <b>파이썬<\/b> 딕셔너리 자료형은 내부적으로 해시 테이블을 가지고 있어 데이터 검색 및 수정이 O(1) 시간에 처리되어 리스트에 비해 빠르게 동작한다. - 딕셔너리 요소 생성 data... ",
			"bloggername":"AngelPlayer`s Diary",
			"bloggerlink":"https:\/\/angelplayer.tistory.com\/",
			"postdate":"20210818"
		},
		{
			"title":"<b>파이썬<\/b> '판다스 데이터 분석' - 판다스 입문",
			"link":"https:\/\/javapp.tistory.com\/155",
			"description":"판다스 공식 홈페이지 pandas - Python Data Analysis Library pandas pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool, built on top of the Python programming... ",
			"bloggername":"Don't Quit ! DOIT 포기하지 말자",
			"bloggerlink":"https:\/\/javapp.tistory.com\/",
			"postdate":"20210702"
		},
		{
			"title":"[<b>파이썬<\/b>] openpyxl 엑셀 열 너비 자동 조절 - 직장인 조모씨",
			"link":"https:\/\/minicode.tistory.com\/183",
			"description":"[<b>파이썬<\/b>] openpyxl 엑셀 열 너비 자동 조절 배움 - 차근차근 기록하자\/[개발] <b>파이썬<\/b> 🍕 \/ 직장인 조모씨... kr 광고 하이인재원 강의, 클래스유 <b>파이썬<\/b>(판다스)으로... ",
			"bloggername":"직장인 조모씨 - 직장인 조모씨",
			"bloggerlink":"https:\/\/minicode.tistory.com\/",
			"postdate":"20220423"
		},
		{
			"title":"[알라딘서재][100자평] 혼자 만들면서 공부하는 <b>파이썬<\/b>",
			"link":"https:\/\/blog.aladin.co.kr\/738900121\/16383385",
			"description":"혼자 만들면서 공부하는 <b>파이썬<\/b> - 37개 라이브러리와 API로 보고서, 차트, 게임, 맵, AI 챗봇 만들기|저자 직강 유튜브 강의, 오픈 채팅 제공 ㅣ 혼자 만들면서 공부하는 시리즈 문현일 지음 \/ 한빛미디어... ",
			"bloggername":"https:\/\/blog.aladin.co.kr\/",
			"bloggerlink":"https:\/\/blog.aladin.co.kr\/738900121",
			"postdate":"20250415"
		},
		{
			"title":"(Python)<b>파이썬<\/b> 실습-<b>파이썬<\/b> 엑셀(Excel)\/<b>파이썬<\/b> 에서 엑셀 작업하기",
			"link":"https:\/\/eunhee-programming.tistory.com\/47",
			"description":"<b>파이썬<\/b>으로 엑셀 작업 <b>파이썬<\/b> 터미널 창에 pip install openpyxl 을 입력하여 openpyxl부터 설치해줍니다. 코드 from openpyxl import Workbook wb=Workbook() #엑셀불러오기 ws=wb.... ",
			"bloggername":"코드짜는 문과녀",
			"bloggerlink":"https:\/\/eunhee-programming.tistory.com\/",
			"postdate":"20210303"
		}
	]
}

In [27]:
for item in result['items']:
    print(item['title'])

[Python] <b>파이썬</b> 문법 (자료형)
<b>파이썬</b> '판다스 데이터 분석' - 판다스 입문
[<b>파이썬</b>] openpyxl 엑셀 열 너비 자동 조절 - 직장인 조모씨
[알라딘서재][100자평] 혼자 만들면서 공부하는 <b>파이썬</b>
(Python)<b>파이썬</b> 실습-<b>파이썬</b> 엑셀(Excel)/<b>파이썬</b> 에서 엑셀 작업하기

In [28]:
import pandas as pd

df = pd.DataFrame(data['items'])
print(df.shape)
df.head()

(5, 6)

,title,link,description,bloggername,bloggerlink,postdate
0,[Python] <b>파이썬</b> 문법 (자료형),https://angelplayer.tistory.com/200,없음 <b>파이썬</b> 딕셔너리 자료형은 내부적으로 해시 테이블을 가지고 있어 데...,AngelPlayer`s Diary,https://angelplayer.tistory.com/,20210818
1,<b>파이썬</b> '판다스 데이터 분석' - 판다스 입문,https://javapp.tistory.com/155,판다스 공식 홈페이지 pandas - Python Data Analysis Libr...,Don't Quit ! DOIT 포기하지 말자,https://javapp.tistory.com/,20210702
2,[<b>파이썬</b>] openpyxl 엑셀 열 너비 자동 조절 - 직장인 조모씨,https://minicode.tistory.com/183,[<b>파이썬</b>] openpyxl 엑셀 열 너비 자동 조절 배움 - 차근차근 ...,직장인 조모씨 - 직장인 조모씨,https://minicode.tistory.com/,20220423
3,[알라딘서재][100자평] 혼자 만들면서 공부하는 <b>파이썬</b>,https://blog.aladin.co.kr/738900121/16383385,"혼자 만들면서 공부하는 <b>파이썬</b> - 37개 라이브러리와 API로 보고서,...",https://blog.aladin.co.kr/,https://blog.aladin.co.kr/738900121,20250415
4,(Python)<b>파이썬</b> 실습-<b>파이썬</b> 엑셀(Excel)/<b>...,https://eunhee-programming.tistory.com/47,<b>파이썬</b>으로 엑셀 작업 <b>파이썬</b> 터미널 창에 pip insta...,코드짜는 문과녀,https://eunhee-programming.tistory.com/,20210303

In [29]:
df = df[['title', 'link', 'bloggername', 'postdate']]
df['title'] = df['title'].str.replace('<.*?>', '', regex=True)
df.head()

,title,link,bloggername,postdate
0,[Python] 파이썬 문법 (자료형),https://angelplayer.tistory.com/200,AngelPlayer`s Diary,20210818
1,파이썬 '판다스 데이터 분석' - 판다스 입문,https://javapp.tistory.com/155,Don't Quit ! DOIT 포기하지 말자,20210702
2,[파이썬] openpyxl 엑셀 열 너비 자동 조절 - 직장인 조모씨,https://minicode.tistory.com/183,직장인 조모씨 - 직장인 조모씨,20220423
3,[알라딘서재][100자평] 혼자 만들면서 공부하는 파이썬,https://blog.aladin.co.kr/738900121/16383385,https://blog.aladin.co.kr/,20250415
4,(Python)파이썬 실습-파이썬 엑셀(Excel)/파이썬 에서 엑셀 작업하기,https://eunhee-programming.tistory.com/47,코드짜는 문과녀,20210303

In [ ]:
search = input('검색어')

params = {
    "query": search,
    "display": 10
}