In [1]:
student = [
    ['홍길동', 20, 1],
    ['이순신', 21, 2],
    ['김유신', 22, 3],
    ['강감찬', 23, 4]
]
student

[['홍길동', 20, 1], ['이순신', 21, 2], ['김유신', 22, 3], ['강감찬', 23, 4]]

In [2]:
import pandas as pd
df = pd.DataFrame(student)
df

     0   1  2
0  홍길동  20  1
1  이순신  21  2
2  김유신  22  3
3  강감찬  23  4

In [3]:
df = pd.DataFrame(student, columns=['이름', '나이', '학년'])
df

    이름  나이  학년
0  홍길동  20   1
1  이순신  21   2
2  김유신  22   3
3  강감찬  23   4

In [4]:
df = pd.DataFrame(student, columns=['이름', '나이', '학년'], index=['a','b','c','d'])
df

    이름  나이  학년
a  홍길동  20   1
b  이순신  21   2
c  김유신  22   3
d  강감찬  23   4

In [5]:
df.info()

<class 'pandas.DataFrame'>
Index: 4 entries, a to d
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      4 non-null      str
 1   나이      4 non-null      int64
 2   학년      4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 128.0+ bytes

In [6]:
# csv 읽어들이기
import pandas as pd
df = pd.read_csv('iphone.csv')
df

      Unnamed: 0         출시일  디스플레이  메모리     출시 버전 Face ID
0       iPhone 7  2016-09-16    4.7  2GB  iOS 10.0      No
1  iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
2       iPhone 8  2017-09-22    4.7  2GB  iOS 11.0      No
3  iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
4       iPhone X  2017-11-03    5.8  3GB  iOS 11.1     Yes
5      iPhone XS  2018-09-21    5.8  4GB  iOS 12.0     Yes
6  iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [7]:
df = pd.read_csv('iphone.csv', header=None)
df

               0           1      2    3         4        5
0            NaN         출시일  디스플레이  메모리     출시 버전  Face ID
1       iPhone 7  2016-09-16    4.7  2GB  iOS 10.0       No
2  iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0       No
3       iPhone 8  2017-09-22    4.7  2GB  iOS 11.0       No
4  iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0       No
5       iPhone X  2017-11-03    5.8  3GB  iOS 11.1      Yes
6      iPhone XS  2018-09-21    5.8  4GB  iOS 12.0      Yes
7  iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0      Yes

In [8]:
# csv 읽어들이기 (0번 열을 인덱스로 지정)
df = pd.read_csv('iphone.csv', index_col=0)
df

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [9]:
df.iloc[1,2]

'3GB'

In [10]:
df.loc['iPhone 7 Plus','메모리']

'3GB'

In [11]:
df.index

Index(['iPhone 7', 'iPhone 7 Plus', 'iPhone 8', 'iPhone 8 Plus', 'iPhone X',
       'iPhone XS', 'iPhone XS Max'],
      dtype='str')

In [13]:
df.iloc[:,2]

iPhone 7         2GB
iPhone 7 Plus    3GB
iPhone 8         2GB
iPhone 8 Plus    3GB
iPhone X         3GB
iPhone XS        4GB
iPhone XS Max    4GB
Name: 메모리, dtype: str

In [16]:
df.loc['iPhone 7':'iPhone 8 Plus', '메모리':'Face ID']

               메모리     출시 버전 Face ID
iPhone 7       2GB  iOS 10.0      No
iPhone 7 Plus  3GB  iOS 10.0      No
iPhone 8       2GB  iOS 11.0      No
iPhone 8 Plus  3GB  iOS 11.0      No

In [17]:
df.loc['iPhone 7':'iPhone 8 Plus', '메모리']

iPhone 7         2GB
iPhone 7 Plus    3GB
iPhone 8         2GB
iPhone 8 Plus    3GB
Name: 메모리, dtype: str

In [18]:
df['디스플레이']

iPhone 7         4.7
iPhone 7 Plus    5.5
iPhone 8         4.7
iPhone 8 Plus    5.5
iPhone X         5.8
iPhone XS        5.8
iPhone XS Max    6.5
Name: 디스플레이, dtype: float64

In [24]:
df.loc[(df['디스플레이']>5) & (df['메모리']=='3GB')]

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes

In [22]:
df.loc[df['디스플레이']>5]

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [25]:
df.loc[df['디스플레이']>5].loc[:,['디스플레이','출시 버전']]

               디스플레이     출시 버전
iPhone 7 Plus    5.5  iOS 10.0
iPhone 8 Plus    5.5  iOS 11.0
iPhone X         5.8  iOS 11.1
iPhone XS        5.8  iOS 12.0
iPhone XS Max    6.5  iOS 12.0

In [27]:
df.loc['iPhone 7 Plus', '출시 버전'] = 'iOS 11.0'
df

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 11.0      No
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [ ]:
df.drop('iPhone 17', axis='index')

In [28]:
df['디스플레이'].sort_values()

iPhone 7         4.7
iPhone 8         4.7
iPhone 7 Plus    5.5
iPhone 8 Plus    5.5
iPhone X         5.8
iPhone XS        5.8
iPhone XS Max    6.5
Name: 디스플레이, dtype: float64

In [29]:
df.sort_values('디스플레이')

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [30]:
import pandas as pd
df = pd.read_csv('gapminder.tsv', sep='\t')
df

          country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   country    1704 non-null   str
 1   continent  1704 non-null   str
 2   year       1704 non-null   int64
 3   lifeExp    1704 non-null   float64
 4   pop        1704 non-null   int64
 5   gdpPercap  1704 non-null   float64
dtypes: float64(2), int64(2), str(2)
memory usage: 80.0 KB

In [35]:
df.head(n=10)

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106
5  Afghanistan      Asia  1977   38.438  14880372  786.113360
6  Afghanistan      Asia  1982   39.854  12881816  978.011439
7  Afghanistan      Asia  1987   40.822  13867957  852.395945
8  Afghanistan      Asia  1992   41.674  16317921  649.341395
9  Afghanistan      Asia  1997   41.763  22227415  635.341351

In [36]:
df.tail()

       country continent  year  lifeExp       pop   gdpPercap
1699  Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700  Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701  Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702  Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703  Zimbabwe    Africa  2007   43.487  12311143  469.709298

In [37]:
df.describe()

             year      lifeExp           pop      gdpPercap
count  1704.00000  1704.000000  1.704000e+03    1704.000000
mean   1979.50000    59.474439  2.960121e+07    7215.327081
std      17.26533    12.917107  1.061579e+08    9857.454543
min    1952.00000    23.599000  6.001100e+04     241.165876
25%    1965.75000    48.198000  2.793664e+06    1202.060309
50%    1979.50000    60.712500  7.023596e+06    3531.846988
75%    1993.25000    70.845500  1.958522e+07    9325.462346
max    2007.00000    82.603000  1.318683e+09  113523.132900

In [38]:
df['country'].value_counts()

country
Afghanistan           12
Albania               12
Algeria               12
Angola                12
Argentina             12
                      ..
Vietnam               12
West Bank and Gaza    12
Yemen, Rep.           12
Zambia                12
Zimbabwe              12
Name: count, Length: 142, dtype: int64

In [39]:
df.corr(numeric_only=True)

               year   lifeExp       pop  gdpPercap
year       1.000000  0.435611  0.082308   0.227318
lifeExp    0.435611  1.000000  0.064955   0.583706
pop        0.082308  0.064955  1.000000  -0.025600
gdpPercap  0.227318  0.583706 -0.025600   1.000000

In [40]:
df.groupby(['year', 'continent'])[['lifeExp', 'gdpPercap']].mean()

                  lifeExp     gdpPercap
year continent
1952 Africa     39.135500   1252.572466
     Americas   53.279840   4079.062552
     Asia       46.314394   5195.484004
     Europe     64.408500   5661.057435
     Oceania    69.255000  10298.085650
1957 Africa     41.266346   1385.236062
     Americas   55.960280   4616.043733
     Asia       49.318544   5787.732940
     Europe     66.703067   6963.012816
     Oceania    70.295000  11598.522455
1962 Africa     43.319442   1598.078825
     Americas   58.398760   4901.541870
     Asia       51.563223   5729.369625
     Europe     68.539233   8365.486814
     Oceania    71.085000  12696.452430
1967 Africa     45.334538   2050.363801
     Americas   60.410920   5668.253496
     Asia       54.663640   5971.173374
     Europe     69.737600  10143.823757
     Oceania    71.310000  14495.021790
1972 Africa     47.450942   2339.615674
     Americas   62.394920   6491.334139
     Asia       57.319269   8187.468699
     Europe     70.775033  12479.575246
     Oceania    71.910000  16417.333380
1977 Africa     49.580423   2585.938508
     Americas   64.391560   7352.007126
     Asia       59.610556   7791.314020
     Europe     71.937767  14283.979110
     Oceania    72.855000  17283.957605
1982 Africa     51.592865   2481.592960
     Americas   66.228840   7506.737088
     Asia       62.617939   7434.135157
     Europe     72.806400  15617.896551
     Oceania    74.290000  18554.709840
1987 Africa     53.344788   2282.668991
     Americas   68.090720   7793.400261
     Asia       64.851182   7608.226508
     Europe     73.642167  17214.310727
     Oceania    75.320000  20448.040160
1992 Africa     53.629577   2281.810333
     Americas   69.568360   8044.934406
     Asia       66.537212   8639.690248
     Europe     74.440100  17061.568084
     Oceania    76.945000  20894.045885
1997 Africa     53.598269   2378.759555
     Americas   71.150480   8889.300863
     Asia       68.020515   9834.093295
     Europe     75.505167  19076.781802
     Oceania    78.190000  24024.175170
2002 Africa     53.325231   2599.385159
     Americas   72.422040   9287.677107
     Asia       69.233879  10174.090397
     Europe     76.700600  21711.732422
     Oceania    79.740000  26938.778040
2007 Africa     54.806038   3089.032605
     Americas   73.608120  11003.031625
     Asia       70.728485  12473.026870
     Europe     77.648600  25054.481636
     Oceania    80.719500  29810.188275