In [1]:
import pandas as pd

df1 = pd.read_csv('concat_1.csv')
df2 = pd.read_csv('concat_2.csv')
df3 = pd.read_csv('concat_3.csv')

In [2]:
df1

    A   B   C   D
0  a0  b0  c0  d0
1  a1  b1  c1  d1
2  a2  b2  c2  d2
3  a3  b3  c3  d3

In [3]:
df2

    A   B   C   D
0  a4  b4  c4  d4
1  a5  b5  c5  d5
2  a6  b6  c6  d6
3  a7  b7  c7  d7

In [4]:
df3

     A    B    C    D
0   a8   b8   c8   d8
1   a9   b9   c9   d9
2  a10  b10  c10  d10
3  a11  b11  c11  d11

In [5]:
concat_df = pd.concat([df1, df2, df3])
concat_df

     A    B    C    D
0   a0   b0   c0   d0
1   a1   b1   c1   d1
2   a2   b2   c2   d2
3   a3   b3   c3   d3
0   a4   b4   c4   d4
1   a5   b5   c5   d5
2   a6   b6   c6   d6
3   a7   b7   c7   d7
0   a8   b8   c8   d8
1   a9   b9   c9   d9
2  a10  b10  c10  d10
3  a11  b11  c11  d11

In [6]:
col_df = pd.concat([df1,df2,df3], axis=1)
col_df

    A   B   C   D   A   B   C   D    A    B    C    D
0  a0  b0  c0  d0  a4  b4  c4  d4   a8   b8   c8   d8
1  a1  b1  c1  d1  a5  b5  c5  d5   a9   b9   c9   d9
2  a2  b2  c2  d2  a6  b6  c6  d6  a10  b10  c10  d10
3  a3  b3  c3  d3  a7  b7  c7  d7  a11  b11  c11  d11

In [7]:
df1.columns = ['A','B','C','D']
df2.columns = ['E','F','G','H']
df3.columns = ['A','C','F','H']

In [8]:
pd.concat([df1,df2,df3])

     A    B    C    D    E    F    G    H
0   a0   b0   c0   d0  NaN  NaN  NaN  NaN
1   a1   b1   c1   d1  NaN  NaN  NaN  NaN
2   a2   b2   c2   d2  NaN  NaN  NaN  NaN
3   a3   b3   c3   d3  NaN  NaN  NaN  NaN
0  NaN  NaN  NaN  NaN   a4   b4   c4   d4
1  NaN  NaN  NaN  NaN   a5   b5   c5   d5
2  NaN  NaN  NaN  NaN   a6   b6   c6   d6
3  NaN  NaN  NaN  NaN   a7   b7   c7   d7
0   a8  NaN   b8  NaN  NaN   c8  NaN   d8
1   a9  NaN   b9  NaN  NaN   c9  NaN   d9
2  a10  NaN  b10  NaN  NaN  c10  NaN  d10
3  a11  NaN  b11  NaN  NaN  c11  NaN  d11

In [9]:
pd.concat([df1,df3],join='inner')

     A    C
0   a0   c0
1   a1   c1
2   a2   c2
3   a3   c3
0   a8   b8
1   a9   b9
2  a10  b10
3  a11  b11

In [10]:
df = pd.read_csv('korean-idol.csv')
df2 = pd.read_csv('korean-idol-2.csv')

In [11]:
df

      이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442

In [12]:
df2

      이름    연봉  가족수
0     지민  3000    3
1   지드래곤  3500    3
2   강다니엘  3200    4
3      뷔  3050    4
4     화사  4300    3
5     정국  2900    5
6     민현  3400    6
7     소연  4500    5
8      진  4200    4
9    하성운  4300    4
10    태연  3700    3
11   차은우  3850    5
12    백호  3900    4
13    JR  4100    3
14    슈가  4150    3

In [13]:
df3 = df2.drop([3, 5, 7, 9])
pd.concat([df, df3], axis=1)

,이름,그룹,소속사,성별,생년월일,키,혈액형,브랜드평판지수,이름,연봉,가족수
0,지민,방탄소년단,빅히트,남자,1995-10-13,173.6,A,10523260,지민,3000.0,3.0
1,지드래곤,빅뱅,YG,남자,1988-08-18,177.0,A,9916947,지드래곤,3500.0,3.0
2,강다니엘,NaN,커넥트,남자,1996-12-10,180.0,A,8273745,강다니엘,3200.0,4.0
3,뷔,방탄소년단,빅히트,남자,1995-12-30,178.0,AB,8073501,NaN,NaN,NaN
4,화사,마마무,RBW,여자,1995-07-23,162.1,A,7650928,화사,4300.0,3.0
5,정국,방탄소년단,빅히트,남자,1997-09-01,178.0,A,5208335,NaN,NaN,NaN
6,민현,뉴이스트,플레디스,남자,1995-08-09,182.3,O,4989792,민현,3400.0,6.0
7,소연,아이들,큐브,여자,1998-08-26,NaN,B,4668615,NaN,NaN,NaN
8,진,방탄소년단,빅히트,남자,1992-12-04,179.2,O,4570308,진,4200.0,4.0
9,하성운,핫샷,스타크루이엔티,남자,1994-03-22,167.1,A,4036489,NaN,NaN,NaN
10,태연,소녀시대,SM,여자,1989-03-09,NaN,A,3918661,태연,3700.0,3.0
11,차은우,아스트로,판타지오,남자,1997-03-30,183.0,B,3506027,차은우,3850.0,5.0
12,백호,뉴이스트,플레디스,남자,1995-07-21,175.0,AB,3301654,백호,3900.0,4.0
13,JR,뉴이스트,플레디스,남자,1995-06-08,176.0,O,3274137,JR,4100.0,3.0
14,슈가,방탄소년단,빅히트,남자,1993-03-09,174.0,O,2925442,슈가,4150.0,3.0

In [14]:
df3 = df3.reset_index(drop=True)
pd.concat([df, df3], axis=1)

,이름,그룹,소속사,성별,생년월일,키,혈액형,브랜드평판지수,이름,연봉,가족수
0,지민,방탄소년단,빅히트,남자,1995-10-13,173.6,A,10523260,지민,3000.0,3.0
1,지드래곤,빅뱅,YG,남자,1988-08-18,177.0,A,9916947,지드래곤,3500.0,3.0
2,강다니엘,NaN,커넥트,남자,1996-12-10,180.0,A,8273745,강다니엘,3200.0,4.0
3,뷔,방탄소년단,빅히트,남자,1995-12-30,178.0,AB,8073501,화사,4300.0,3.0
4,화사,마마무,RBW,여자,1995-07-23,162.1,A,7650928,민현,3400.0,6.0
5,정국,방탄소년단,빅히트,남자,1997-09-01,178.0,A,5208335,진,4200.0,4.0
6,민현,뉴이스트,플레디스,남자,1995-08-09,182.3,O,4989792,태연,3700.0,3.0
7,소연,아이들,큐브,여자,1998-08-26,NaN,B,4668615,차은우,3850.0,5.0
8,진,방탄소년단,빅히트,남자,1992-12-04,179.2,O,4570308,백호,3900.0,4.0
9,하성운,핫샷,스타크루이엔티,남자,1994-03-22,167.1,A,4036489,JR,4100.0,3.0
10,태연,소녀시대,SM,여자,1989-03-09,NaN,A,3918661,슈가,4150.0,3.0
11,차은우,아스트로,판타지오,남자,1997-03-30,183.0,B,3506027,NaN,NaN,NaN
12,백호,뉴이스트,플레디스,남자,1995-07-21,175.0,AB,3301654,NaN,NaN,NaN
13,JR,뉴이스트,플레디스,남자,1995-06-08,176.0,O,3274137,NaN,NaN,NaN
14,슈가,방탄소년단,빅히트,남자,1993-03-09,174.0,O,2925442,NaN,NaN,NaN

In [15]:
pd.merge(df, df3, on='이름', how='left')

      이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수      연봉  가족수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260  3000.0  3.0
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947  3500.0  3.0
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745  3200.0  4.0
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501     NaN  NaN
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928  4300.0  3.0
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335     NaN  NaN
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792  3400.0  6.0
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615     NaN  NaN
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308  4200.0  4.0
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489     NaN  NaN
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661  3700.0  3.0
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027  3850.0  5.0
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654  3900.0  4.0
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137  4100.0  3.0
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442  4150.0  3.0

In [17]:
pd.merge(df, df3, left_on='이름', right_on='성함', how='outer')

,이름,그룹,소속사,성별,생년월일,키,혈액형,브랜드평판지수,성함,연봉,가족수
0,JR,뉴이스트,플레디스,남자,1995-06-08,176.0,O,3274137,JR,4100.0,3.0
1,강다니엘,NaN,커넥트,남자,1996-12-10,180.0,A,8273745,강다니엘,3200.0,4.0
2,민현,뉴이스트,플레디스,남자,1995-08-09,182.3,O,4989792,민현,3400.0,6.0
3,백호,뉴이스트,플레디스,남자,1995-07-21,175.0,AB,3301654,백호,3900.0,4.0
4,뷔,방탄소년단,빅히트,남자,1995-12-30,178.0,AB,8073501,NaN,NaN,NaN
5,소연,아이들,큐브,여자,1998-08-26,NaN,B,4668615,NaN,NaN,NaN
6,슈가,방탄소년단,빅히트,남자,1993-03-09,174.0,O,2925442,슈가,4150.0,3.0
7,정국,방탄소년단,빅히트,남자,1997-09-01,178.0,A,5208335,NaN,NaN,NaN
8,지드래곤,빅뱅,YG,남자,1988-08-18,177.0,A,9916947,지드래곤,3500.0,3.0
9,지민,방탄소년단,빅히트,남자,1995-10-13,173.6,A,10523260,지민,3000.0,3.0
10,진,방탄소년단,빅히트,남자,1992-12-04,179.2,O,4570308,진,4200.0,4.0
11,차은우,아스트로,판타지오,남자,1997-03-30,183.0,B,3506027,차은우,3850.0,5.0
12,태연,소녀시대,SM,여자,1989-03-09,NaN,A,3918661,태연,3700.0,3.0
13,하성운,핫샷,스타크루이엔티,남자,1994-03-22,167.1,A,4036489,NaN,NaN,NaN
14,화사,마마무,RBW,여자,1995-07-23,162.1,A,7650928,화사,4300.0,3.0

In [18]:
df2 = df.copy()

In [19]:
df2.isnull().sum()

이름         0
그룹         1
소속사        0
성별         0
생년월일       0
키          2
혈액형        0
브랜드평판지수    0
dtype: int64

In [20]:
df2.dropna()

      이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442

In [ ]:
df2['키'].fillna(df2['키'].mean())

In [21]:
df2['키'] = df2['키'].fillna(df2['키'].mean())
df2

      이름     그룹      소속사  성별        생년월일           키 혈액형   브랜드평판지수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.600000   A  10523260
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.000000   A   9916947
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.000000   A   8273745
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.000000  AB   8073501
4     화사    마마무      RBW  여자  1995-07-23  162.100000   A   7650928
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.000000   A   5208335
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.300000   O   4989792
7     소연    아이들       큐브  여자  1998-08-26  175.792308   B   4668615
8      진  방탄소년단      빅히트  남자  1992-12-04  179.200000   O   4570308
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.100000   A   4036489
10    태연   소녀시대       SM  여자  1989-03-09  175.792308   A   3918661
11   차은우   아스트로     판타지오  남자  1997-03-30  183.000000   B   3506027
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.000000  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.000000   O   3274137
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.000000   O   2925442

In [22]:
df2['키'].astype(int)

0     173
1     177
2     180
3     178
4     162
5     178
6     182
7     175
8     179
9     167
10    175
11    183
12    175
13    176
14    174
Name: 키, dtype: int64

In [23]:
pd.to_datetime(df2['생년월일'])

0    1995-10-13
1    1988-08-18
2    1996-12-10
3    1995-12-30
4    1995-07-23
5    1997-09-01
6    1995-08-09
7    1998-08-26
8    1992-12-04
9    1994-03-22
10   1989-03-09
11   1997-03-30
12   1995-07-21
13   1995-06-08
14   1993-03-09
Name: 생년월일, dtype: datetime64[us]

In [24]:
df = pd.DataFrame({'a':[10,20,30], 'b':[20,30,40]})
df

    a   b
0  10  20
1  20  30
2  30  40

In [25]:
# 함수 선언
# 제곱함수
def func_sq(x):
    return x ** 2
# n제곱함수
def func_exp(x, n):
    return x ** n

In [26]:
df['a'].apply(func_sq)

0    100
1    400
2    900
Name: a, dtype: int64

In [27]:
df['a'].apply(func_exp, n=3)

0     1000
1     8000
2    27000
Name: a, dtype: int64

In [28]:
def mean(col) :
    sum = 0
    for i in col:
        sum += i
    return sum / len(col)

In [30]:
df.apply(mean, axis=1)

0    15.0
1    25.0
2    35.0
dtype: float64

In [31]:
df = pd.read_csv('korean-idol.csv')
df

      이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442

In [32]:
df.loc[df['성별'] == '남자', '성별'] = '1'
df.loc[df['성별'] == '여자', '성별'] = '0'
df

      이름     그룹      소속사 성별        생년월일      키 혈액형   브랜드평판지수
0     지민  방탄소년단      빅히트  1  1995-10-13  173.6   A  10523260
1   지드래곤     빅뱅       YG  1  1988-08-18  177.0   A   9916947
2   강다니엘    NaN      커넥트  1  1996-12-10  180.0   A   8273745
3      뷔  방탄소년단      빅히트  1  1995-12-30  178.0  AB   8073501
4     화사    마마무      RBW  0  1995-07-23  162.1   A   7650928
5     정국  방탄소년단      빅히트  1  1997-09-01  178.0   A   5208335
6     민현   뉴이스트     플레디스  1  1995-08-09  182.3   O   4989792
7     소연    아이들       큐브  0  1998-08-26    NaN   B   4668615
8      진  방탄소년단      빅히트  1  1992-12-04  179.2   O   4570308
9    하성운     핫샷  스타크루이엔티  1  1994-03-22  167.1   A   4036489
10    태연   소녀시대       SM  0  1989-03-09    NaN   A   3918661
11   차은우   아스트로     판타지오  1  1997-03-30  183.0   B   3506027
12    백호   뉴이스트     플레디스  1  1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  1  1995-06-08  176.0   O   3274137
14    슈가  방탄소년단      빅히트  1  1993-03-09  174.0   O   2925442

In [35]:
# 성별 매핑 딕셔너리
gender_map = {
    '남자': '1',
    '여자': '0'
}

In [36]:
df['성별'].map(gender_map)

0     1
1     1
2     1
3     1
4     0
5     1
6     1
7     0
8     1
9     1
10    0
11    1
12    1
13    1
14    1
Name: 성별, dtype: str

In [37]:
gender_map

{'남자': '1', '여자': '0'}

In [38]:
df['혈액형'].value_counts()

혈액형
A     7
O     4
AB    2
B     2
Name: count, dtype: int64

In [39]:
pd.get_dummies(df['혈액형'], prefix='혈액형')

    혈액형_A  혈액형_AB  혈액형_B  혈액형_O
0    True   False  False  False
1    True   False  False  False
2    True   False  False  False
3   False    True  False  False
4    True   False  False  False
5    True   False  False  False
6   False   False  False   True
7   False   False   True  False
8   False   False  False   True
9    True   False  False  False
10   True   False  False  False
11  False   False   True  False
12  False    True  False  False
13  False   False  False   True
14  False   False  False   True

In [40]:
pd.get_dummies(df['혈액형'], prefix='혈액형', dtype=int)

    혈액형_A  혈액형_AB  혈액형_B  혈액형_O
0       1       0      0      0
1       1       0      0      0
2       1       0      0      0
3       0       1      0      0
4       1       0      0      0
5       1       0      0      0
6       0       0      0      1
7       0       0      1      0
8       0       0      0      1
9       1       0      0      0
10      1       0      0      0
11      0       0      1      0
12      0       1      0      0
13      0       0      0      1
14      0       0      0      1

In [41]:
pd.concat([df, pd.get_dummies(df['혈액형'], prefix='혈액형', dtype=int)], axis=1)

,이름,그룹,소속사,성별,생년월일,키,혈액형,브랜드평판지수,혈액형_A,혈액형_AB,혈액형_B,혈액형_O
0,지민,방탄소년단,빅히트,남자,1995-10-13,173.6,A,10523260,1,0,0,0
1,지드래곤,빅뱅,YG,남자,1988-08-18,177.0,A,9916947,1,0,0,0
2,강다니엘,NaN,커넥트,남자,1996-12-10,180.0,A,8273745,1,0,0,0
3,뷔,방탄소년단,빅히트,남자,1995-12-30,178.0,AB,8073501,0,1,0,0
4,화사,마마무,RBW,여자,1995-07-23,162.1,A,7650928,1,0,0,0
5,정국,방탄소년단,빅히트,남자,1997-09-01,178.0,A,5208335,1,0,0,0
6,민현,뉴이스트,플레디스,남자,1995-08-09,182.3,O,4989792,0,0,0,1
7,소연,아이들,큐브,여자,1998-08-26,NaN,B,4668615,0,0,1,0
8,진,방탄소년단,빅히트,남자,1992-12-04,179.2,O,4570308,0,0,0,1
9,하성운,핫샷,스타크루이엔티,남자,1994-03-22,167.1,A,4036489,1,0,0,0
10,태연,소녀시대,SM,여자,1989-03-09,NaN,A,3918661,1,0,0,0
11,차은우,아스트로,판타지오,남자,1997-03-30,183.0,B,3506027,0,0,1,0
12,백호,뉴이스트,플레디스,남자,1995-07-21,175.0,AB,3301654,0,1,0,0
13,JR,뉴이스트,플레디스,남자,1995-06-08,176.0,O,3274137,0,0,0,1
14,슈가,방탄소년단,빅히트,남자,1993-03-09,174.0,O,2925442,0,0,0,1

# 실습 코드

In [60]:
import glob
import pandas as pd

In [61]:
files = glob.glob("./매출내역/월별매출내역_*.xlsx")
files

['./매출내역/월별매출내역_11월.xlsx',
 './매출내역/월별매출내역_6월.xlsx',
 './매출내역/월별매출내역_10월.xlsx',
 './매출내역/월별매출내역_7월.xlsx',
 './매출내역/월별매출내역_12월.xlsx',
 './매출내역/월별매출내역_5월.xlsx',
 './매출내역/월별매출내역_4월.xlsx',
 './매출내역/월별매출내역_1월.xlsx',
 './매출내역/월별매출내역_8월.xlsx',
 './매출내역/월별매출내역_9월.xlsx',
 './매출내역/월별매출내역_2월.xlsx',
 './매출내역/월별매출내역_3월.xlsx']

In [62]:
total = pd.DataFrame()

for file in files:
    df = pd.read_excel(file, skiprows=range(6)).iloc[:,1:]
    total = pd.concat([total, df], ignore_index=True)

print(len(total))
total.head()

18229

          일자  지점    품명  수량 주문회원ID            수령 주소 주문 상태  결제 수단
0 2023-11-01  강남  스파게티   5  ID303    서울특별시 강서구 화곡동  배송완료  인터넷뱅킹
1 2023-11-01  분당   리조또   2  ID486    서울특별시 용산구 산천동  주문완료   신용카드
2 2023-11-01  강남   샐러드  11  ID165    서울특별시 금천구 가산동  배송완료  인터넷뱅킹
3 2023-11-01  분당   파스타  11   ID44  서울특별시 용산구 원효로3가  주문완료  무통장입금
4 2023-11-01  종로   파스타   6  ID281    서울특별시 마포구 상수동  주문완료  인터넷뱅킹

In [63]:
price = pd.read_excel("./매출내역/상품가격.xlsx")
price = price.transpose()
price.head()

          0
제품       가격
돈까스   20000
샐러드    5000
파스타   10000
스파게티   8000

In [64]:
price_dict = price.iloc[1:, 0].to_dict()
price_dict

{'돈까스': 20000,
 '샐러드': 5000,
 '파스타': 10000,
 '스파게티': 8000,
 '스테이크': 30000,
 '리조또': 15000}

In [65]:
total['가격'] = total['품명'].map(price_dict)
total.head()

          일자  지점    품명  수량 주문회원ID            수령 주소 주문 상태  결제 수단     가격
0 2023-11-01  강남  스파게티   5  ID303    서울특별시 강서구 화곡동  배송완료  인터넷뱅킹   8000
1 2023-11-01  분당   리조또   2  ID486    서울특별시 용산구 산천동  주문완료   신용카드  15000
2 2023-11-01  강남   샐러드  11  ID165    서울특별시 금천구 가산동  배송완료  인터넷뱅킹   5000
3 2023-11-01  분당   파스타  11   ID44  서울특별시 용산구 원효로3가  주문완료  무통장입금  10000
4 2023-11-01  종로   파스타   6  ID281    서울특별시 마포구 상수동  주문완료  인터넷뱅킹  10000

In [66]:
total['매출금액'] = total['수량'] * total['가격']
total.head()

          일자  지점    품명  수량 주문회원ID            수령 주소 주문 상태  결제 수단     가격    매출금액
0 2023-11-01  강남  스파게티   5  ID303    서울특별시 강서구 화곡동  배송완료  인터넷뱅킹   8000   40000
1 2023-11-01  분당   리조또   2  ID486    서울특별시 용산구 산천동  주문완료   신용카드  15000   30000
2 2023-11-01  강남   샐러드  11  ID165    서울특별시 금천구 가산동  배송완료  인터넷뱅킹   5000   55000
3 2023-11-01  분당   파스타  11   ID44  서울특별시 용산구 원효로3가  주문완료  무통장입금  10000  110000
4 2023-11-01  종로   파스타   6  ID281    서울특별시 마포구 상수동  주문완료  인터넷뱅킹  10000   60000

In [67]:
total['일자'] = pd.to_datetime(total['일자'])
total['월'] = total['일자'].dt.month
total[['일자','월']].head()

          일자   월
0 2023-11-01  11
1 2023-11-01  11
2 2023-11-01  11
3 2023-11-01  11
4 2023-11-01  11

In [68]:
result = total.groupby(['월', '지점'])['매출금액'].sum().reset_index()
result

     월  지점      매출금액
0    1  강남  10796000
1    1  분당  40624000
2    1  종로  30934000
3    1  홍대  21475000
4    2  강남  10595000
5    2  분당  39006000
6    2  종로  28052000
7    2  홍대  17178000
8    3  강남  10375000
9    3  분당  37769000
10   3  종로  32980000
11   3  홍대  19799000
12   4  강남  10829000
13   4  분당  44905000
14   4  종로  33534000
15   4  홍대  21873000
16   5  강남   9729000
17   5  분당  39947000
18   5  종로  30480000
19   5  홍대  20354000
20   6  강남  12035000
21   6  분당  42393000
22   6  종로  26445000
23   6  홍대  20046000
24   7  강남  12181000
25   7  분당  40612000
26   7  종로  29760000
27   7  홍대  22620000
28   8  강남  11102000
29   8  분당  38091000
30   8  종로  33570000
31   8  홍대  18915000
32   9  강남   8148000
33   9  분당  44548000
34   9  종로  31550000
35   9  홍대  22290000
36  10  강남  10198000
37  10  분당  44286000
38  10  종로  32127000
39  10  홍대  20643000
40  11  강남   8703000
41  11  분당  37623000
42  11  종로  28346000
43  11  홍대  20948000
44  12  강남  11100000
45  12  분당  42333000
46  12  종로  28370000
47  12  홍대  20377000

In [70]:
ew = pd.ExcelWriter('result.xlsx', engine='xlsxwriter')
result.to_excel(ew, index=False)
ew.close()